### PR TITLE
Add net import share contraints

### PR DESCRIPTION
**Pull request by timtroendle**
Fixes issue(s) #270 

Summary of changes in this pull request:

* add a new constraint constraining net imports

Reviewer checklist:

- [x] Test(s) added to cover contribution
- [x] Documentation updated
- [ ] Changelog updated
- [x] Coverage maintained or improved

### CODE REVIEW

**Comment by timtroendle** [comment]
Unfortunately, one cannot explicitly define a transmission tech -- at least I do not manage to. I wrote a failing test. However, if you do not define techs, you'll receive warnings.

**Comment by sjpfenninger** [comment]
I think this is fine, but perhaps the docs should mention that one cannot explicitly select transmission techs with this constraint (only implicitly via carriers). What warnings do you receive?
Also can you update CHANGELOG. Otherwise looks good.

**Comment by timtroendle** [comment]
> What warnings do you receive?

When no tech is specified, one sees this warning:

>   * All technologies were requested for inclusion in group constraint `example_net_import_share_constraint`, but those from tech group(s) `['conversion', 'conversion_plus', 'demand', 'storage', 'supply', 'supply_plus']` have been ignored as one or more of the constraints cannot be applied to technologies in these groups

When a tech is specified, one sees this warning which turns into an error lateron:

> * Group constraint `example_net_import_share_constraint` cannot be applied as there are no valid loc_tech combinations available.

**Comment by sjpfenninger** [comment]
Ok, I'm willing to merge this as-is for now with the intention of it being cleaned up later. @timtroendle can you open an issue linking to this PR to track the facts that (1) we need to deal with transmission techs in `techs:` here properly and (2) we need to revisit what warnings are raised for this kind of constraint?

**Pull request merged**
