### PR TITLE
Blacken

### PR DESCRIPTION
**Pull request by suvayu**
* Add `pyproject.toml` with black configurations
* Blacken

### CODE REVIEW

**Comment by brynpickering** [comment]
Mind fixing the few 'unresolved' Hound violations @suvayu? I know they're not your doing, but it seems cleaner to fix them here

**Comment by sjpfenninger** [comment]
> Mind fixing the few 'unresolved' Hound violations @suvayu? I know they're not your doing, but it seems cleaner to fix them here

For some of these, we either need to adjust Black config or change the flake8 config Hound uses. Especially the ones related to space before or after ':' and ','. Manually fixing these now means they will come back every time somebody touches the files in question.

`use ==/!= to compare str, bytes, and int literals` seems to be something we messed up and should fix, though

**Comment by sjpfenninger** [comment]
Also the question whether we still need Hound at all if Black is always run. A black CI job that runs on PRs perhaps?

**Comment by suvayu** [comment]
> For some of these, we either need to adjust Black config or change the flake8 config Hound uses. Especially the ones related to space before or after ':' and ','. Manually fixing these now means they will come back every time somebody touches the files in question.

Yes, some of Hound's complaints conflict with `black`, the `:` is one such example.  I fixed the ones that are not.

PS: Inadvertently I tagged a random github user in the commit message when referring to Hound, so I force pushed to remove that.

**Comment by suvayu** [comment]
Should I rerun black with line length set to 88?

**Comment by sjpfenninger** [comment]
Didn't you run it with 88 already?

**Comment by sjpfenninger** [comment]
I guess we use pre-commit integration as per https://black.readthedocs.io/en/stable/version_control_integration.html ? I've added a `.pre-commit-config.yaml` accordingly. What would be left is to update the developer docs and maybe README.md (code-style black badge, etc)?

**Comment by suvayu** [comment]
This seems to work.  I wasn't aware of `pre-commit`, I was thinking of writing pre-commit hooks ourselves.

While this integrates nicely for a correctly setup environment, it does not stop a contributor from committing without running black if they have not setup `pre-commit`.  The only way to do that is to add the generated hooks in the repo, unfortunately we can't because there are references to the local python installation in the script that is generated.

Thoughts?

**Comment by sjpfenninger** [comment]
I think we just use `pre-commit`, documenting it in the developer docs, and relying on people following those. To protect us, [Hound apparently uses `flake8-black`](https://github.com/houndci/hound/issues/1769) so it should warn if a PR isn't properly blacked, and PR authors can then be told to use black.

**Comment by brynpickering** [comment]
> I think we just use `pre-commit`, documenting it in the developer docs, and relying on people following those. To protect us, [Hound apparently uses `flake8-black`](https://github.com/houndci/hound/issues/1769) so it should warn if a PR isn't properly blacked, and PR authors can then be told to use black.

OK, so all that seems to remain is updates to the documentation!

**Comment by suvayu** [comment]
I updated the contribution guidelines, please have a look.  I also added `pre-commit` to `requirements/dev_tools.yml`, although I'm not sure what's the format of those files.  I couldn't create a conda environment out of it.

    CondaValueError: could not parse 'name: calliope' in: requirements/dev_tools.yml

Maybe there are relics from the past?

**Comment by brynpickering** [comment]
@sjpfenninger I think I'll leave this to you to look over one last time, since it's my docs changes that still might need checking ;)


> Maybe they are relics from the past?

@suvayu They get dragged into a [util function](utils/conda_create.py) to create conda environments from multiple requirement files. Not sure if there's now a more elegant way of doing it...

**Comment by sjpfenninger** [comment]
@brynpickering @suvayu I cleaned up the requirements so there is a single requirements.yml file that can be used with ``conda env create -f requirements.yml`` (just tested it, works without issues and uses the most recent Python version as we don't specify it, which is a behaviour that works for our purposes I think).

I think there is no point in separating "dev" and "non-dev" requirements since anybody cloning the repository directly is running it for dev purposes anyway.

@brynpickering ``conda_create.py`` is really just an internal utility for CI use and we shouldn't force it on people. I expunged it from the docs again.

While I was at it I cleaned out some the profiling bits from the Makefiles and requirements. If people want to do profiling I think they use whatever they want, no need to specify that here.

**Comment by sjpfenninger** [comment]
@suvayu I guess this is a good candidate for not squashing into a single commit, how do we best clean it up? (e.g. all blackening is squashed into one commit, config updates into one or a few others)

**Comment by suvayu** [comment]
> @suvayu I guess this is a good candidate for not squashing into a single commit, how do we best clean it up? (e.g. all blackening is squashed into one commit, config updates into one or a few others)

Yes, something like that.  Unfortunately can't do that on github, need to use the CLI, `git rebase -i ...` followed by a force push.

**Comment by suvayu** [comment]
@sjpfenninger @brynpickering Since this branch would be overwritten, I have pushed it to a [temporary branch](https://github.com/calliope-project/calliope/tree/tmp_blacken).  If this is okay, let me know, I will push it here.

**Comment by suvayu** [comment]
@sjpfenninger I didn't realise the tests are failing.  I don't think I can debug this, it's something to do with `pyomo`:

```
==================================== ERRORS ====================================
_______ ERROR at setup of TestUpdateParam.test_update_param_multiple_dim _______
[gw0] linux -- Python 3.7.6 /usr/share/miniconda/envs/calliope/bin/python

    @pytest.fixture(scope="class")
    def model():
        m = build_model({}, "simple_supply,two_hours,investment_costs")
>       m.run()

calliope/test/test_backend_pyomo_interface.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
calliope/core/model.py:259: in run
    self._model_data, self._timings, **kwargs
calliope/backend/run.py:49: in run
    build_only=build_only,
calliope/backend/run.py:103: in run_plan
    save_logs=save_logs,
calliope/backend/pyomo/model.py:224: in solve_model
    results = opt.solve(backend_model, tee=True, **solve_kwargs)
/usr/share/miniconda/envs/calliope/lib/python3.7/site-packages/pyomo/opt/base/solvers.py:516: in solve
    self.available(exception_flag=True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pyomo.solvers.plugins.solvers.CBCplugin.CBCSHELL object at 0x7eff67b2ba50>
exception_flag = True

    def available(self, exception_flag=False):
        """ True if the solver is available """
        if self._assert_available:
            return True
        if not OptSolver.available(self,exception_flag):
            return False
        try:
            ans = self.executable()
        except NotImplementedError:
            ans = None
        if ans is None:
            if exception_flag:
                msg = "No executable found for solver '%s'"
>               raise ApplicationError(msg % self.name)
E               pyutilib.common._exceptions.ApplicationError: No executable found for solver 'cbc'

/usr/share/miniconda/envs/calliope/lib/python3.7/site-packages/pyomo/opt/solver/shellcmd.py:118: ApplicationError
```

**Comment by sjpfenninger** [comment]
@suvayu Tests should be passing now. The temporary branch looks good to me, happy for you to force-push that here.

**Pull request merged**
