### PR TITLE
Add shadow prices (duals)

### PR DESCRIPTION
**Pull request by brynpickering**
Fixes issue(s) #283 

Summary of changes in this pull request:

* Add a pyomo solver data importer for duals
* Add a backend getter method to access these for constraints.

Example:

```python
[In]:
import calliope
m = calliope.examples.national_scale()
m.build()
m.backend.shadow_prices.activate()
m.solve()
m.backend.shadow_prices.get("system_balance").to_series().head()

[Out]:
nodes    carriers  timesteps          
region1  power     2005-01-01 00:00:00    0.04
                   2005-01-01 01:00:00    0.04
                   2005-01-01 02:00:00    0.04
                   2005-01-01 03:00:00    0.04
                   2005-01-01 04:00:00    0.04
Name: system_balance, dtype: object
```

## TODO:

- [x] tests
- [ ] handle trying to access duals for MILP models (only pure LP models have duals)
- [x] check if there is a time/memory overhead to switching on dual capturing
- [ ] docs

Reviewer checklist:

- [x] Test(s) added to cover contribution
- [ ] Documentation updated
- [ ] Changelog updated
- [ ] Coverage maintained or improved

### CODE REVIEW

**Comment by brynpickering** [comment]
Quite considerable memory footprint created by having dual tracking activated in pyomo:

without dual tracking:
image

with dual tracking:
image

Heap size peak changes from 204MB to 370MB for this example case (urban scale, 2 months).

Have updated the implementation to be deactivated by default and to allow user activatation. It also deactivates automatically if trying to run using CBC solver.

**Comment by brynpickering** [comment]
I wouldn't do anything special for dealing with duals in MILP models. The default in Pyomo is just to return None instead of a value, so I think that's fine?

**Comment by brynpickering** [comment]
My implementation of shadow prices as a class attribute of the BackendModel is in the directio of how I'd imagine implementing #510.

**Review by sjpfenninger — APPROVED** [review]

**Comment by sjpfenninger** [comment]
Will updated changelog and docs later this week

**Pull request merged**
