### PR TITLE
Fix time masking when set_t.csv contains sub-hourly resolutions

### LINKED ISSUE #81: Time masking fails with set_t.csv containing sub-hourly resolutions
Using a set_t.csv file with 15 minute intervals and applying the following time mask:
`time:
    masks:
        {function: week, options: {day_func: 'extreme', tech: 'demand_power', how: 'max'}}
    function: resample
    function_options: {'resolution': '6H'}`

Generates an InvalidIndexError due to duplication, as the time masking functions appear to ignore any sub-hourly component of the timestamp. Changing set_t.csv to hourly timesteps for otherwise identical model corrects the issue.

### PR DESCRIPTION
**Pull request by GraemeHawker**
Fixes #81

### CODE REVIEW

**Comment by brynpickering** [comment]
I've tested it in a few cases, seems to work as expected. Could you rename the commit to be something more explicit? Thanks!

**Comment by sjpfenninger** [comment]
Thanks a lot @GraemeHawker!

Looks good to me (just closed/reopened to try and get hound to re-run checks, which didn't seem to work), so am merging.

**Comment by GraemeHawker** [comment]
Yeah, sorry for lack of commit msg - slip of the keyboard. Tried to amend and force push but got a permissions error - maybe because once the PR is created I need master rights to do so?

Also, while I'm familiar with git I'm fairly new to github flow - let me know if there's any preferred practices I'm not following, as I'm planning on doing a few more issues and PRs over the next week or so relating to the models I've been working on.

(i.e. not clear what hound is failing on as it gives no details - is it basically applying the same rules as pylint?)

**Comment by sjpfenninger** [comment]
No prob. Generally fine to open PRs, just with more descriptive titles and commit messages ;)

We want to extend our developer docs a little bit with more info on how to contribute soon, so if you note down things that are not quite clear from somebody approaching the project for the first time, that would be helpful!

Yes, hound is supposed to run pylint but I think we had a bad config file so it didn't actually run. Nothing to do with your PR!

**Pull request merged**
