### PR TITLE
Rename dimensions to dims in docs

### LINKED ISSUE #612: Outdated 'dimensions' formalism in some parts of the docs
### Description

Some parts of the docs, e.g. the [Math syntax](https://calliope.readthedocs.io/en/v0.7.0.dev3/user_defined_math/syntax/), still suggest using `dimensions` as a string to specify dimensions for parameters of other pieces of math in the yaml files.

This is, however, outdated. The latest formalism is `dims`.

### Related links

- https://calliope.readthedocs.io/en/v0.7.0.dev3/user_defined_math/syntax/

### Version

0.7.0dev3

### Proposed change

Systematically search through the docs to find and replace `dimensionos:` with `dims:` in code snippets.

### PR DESCRIPTION
**Pull request by brynpickering**
Fixes #612 

## Reviewer checklist

- [ ] Test(s) added to cover contribution
- [ ] Documentation updated
- [x] Changelog updated
- [ ] Coverage maintained or improved

### CODE REVIEW

**Review by irm-codebase — CHANGES_REQUESTED** [review]
After doing a quick search, I found "dimensions" being used in quite some parts of the code.
- We still use `add_dimensions`, not `add_dims`
- A lot of internal docstrings / code use `dimensions`, but asking to fix that would be too much.

Would it be possible to update `add_dimensions:` for consistency?

**Comment by brynpickering** [comment]
This is something @sjpfenninger and I went back and forth on a lot. Would you prefer `dimensions` and `add_dimensions` everywhere, or `dims` and `add_dims` @irm-codebase @FLomb ?

**Comment by FLomb** [comment]
> This is something @sjpfenninger and I went back and forth on a lot. Would you prefer `dimensions` and `add_dimensions` everywhere, or `dims` and `add_dims` @irm-codebase @FLomb ?

I don't have a strong preference for either of the two, but I agree it'd be nice to have consistency across all functions for which the "dimension" concept is part of the name.

**Comment by irm-codebase** [comment]
@brynpickering : I agree with Francesco. 

`dims` is shorter, and probably more enjoyable for users. I think it's fine to keep it, but we need to make sure that all the user-side code / YAML stuff sticks to that convention. Basically:

User-side:
- If it is a variable or parameter, use `dims`.
- If it's documentation talking about it, either `dims` or dimensions is fine (we do this for `techs` / technology, with little complaints).
Internally (code variables and docstrings): 
- Use either. Not really enforceable, and kind of a waste of time to pursue full consistency imo. If the code is clear it is a non issue.

**Review by irm-codebase — APPROVED** [review]
Looks great!

**Pull request merged**
